[package]
name = "async_iot_host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "async_iot_server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0"
async_iot_models = { path = "../async_iot_models" }
crossterm = { version = "0" }
http-types = "2"
lazy_static = "1"
thiserror = "1"
tide = { version = "0" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
